invoice_no=input("Enter the invoice number: ")
customer_name=input("Enter the customer name: ")
amount_due=float(input("Enter the amount due: "))
print("=" * 30)
print("Invoice".upper().center(30))
print(f"Invoice No: INV-{str(invoice_no).rjust(5,'0')}".center(30))
print(f"Customer: {customer_name.title()}".center(30))
print(f"Amount: ${amount_due:.2f}".center(30))
print("=" * 30)